### ISSUE TITLE
sessions = 'all' does not work

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-bids-pipeline#475] opened 2021-11-22 19:52 UTC
Contrary to what the documentation suggests, one cannot trust in `sessions = 'all'` but instead needs to provide a list of all sessions. This should not be, right?

cc @hoechenberger @agramfort

**Comment by agramfort** [comment] 2021-11-22 19:55
what do you expect in this case? get all epochs from all sessions into one
-epo file?

>

**Comment by dengemann** [comment] 2021-11-22 19:58
simply the same behavior as `sessions = ['A', 'B', 'C']`, that is: process all sessions within their respective folders.

**Comment by agramfort** [comment] 2021-11-22 20:24
so it's as running the pipeline for all sessions one after the other right?
if so I think we
should avoid complexifying the code and just enforce that the pipeline is
run for each
session by the user

my 2c

>

**Comment by dengemann** [comment] 2021-11-22 22:20
Yes that's the expected behavior based on the current API.

I am trying to say that

```sessions = 'all'```

which is supported by current documentation, should do the same as

```sessions = ['A', 'B', 'C']```

if there are sessions A, B, C.

Instead `sessions = 'all'` crashes.

Hope it's getting clearer.

**Comment by hoechenberger** [comment] 2021-11-23 09:27
Actually it **should** work – we have code specifically for that use case. I'm looking into it now, there seems to be a bug somewhere. So this is clearly a bug and not a missing feature.

**Comment by dengemann** [comment] 2021-11-23 09:30
That's what I was trying to do tell you :D not a feature request.

**Comment by hoechenberger** [comment] 2021-11-23 09:33
😅 Looking into this now! Will keep you posted.

**Comment by hoechenberger** [comment] 2021-11-23 09:42
@dengemann I cannot reproduce, are you sure your dataset is BIDS-compliant? Can you share the dataset?

**Comment by dengemann** [comment] 2021-11-23 09:44
I could try to generate some fake data that match this data.

**Comment by hoechenberger** [comment] 2021-11-23 09:52
Can you try to run the BIDS validator on your data first?

```
npm install -g bids-validator
bids-validator /path/to/dataset
```

**Comment by hoechenberger** [comment] 2022-04-21 07:18
I'm closing this for now but feel to reopen should you run into this issue again. I failed to reproduce.

**Closed** 2022-04-21 07:18 UTC
Labels: bug
