### ISSUE TITLE
"split" entity incorrectly added to expected emtpy-room filename to when using n_jobs > 1

### ISSUE THREAD

**Issue by crsegerie** [mne-tools/mne-bids-pipeline#376] opened 2021-06-10 13:48 UTC
When I use the parameter N_JOBS = 5, with several subjects, I get an error. While when I use N_JOBS = 1 everything is fine. When I use N_JOBS = 5, the error comes from the fact that my file is called `sub-197_task-noise_proc-filt_raw.fif` and not `sub-197_task-noise_proc-filt_split-01_raw.fif` : 

> 15:30:03 [Step-02][sub-197, run-02] Resampling empty-room recording.
> 15:30:04  A critical error occurred.
> joblib.externals.loky.process_executor._RemoteTraceback:
> """
> Traceback (most recent call last):
>   File "/storage/store/work/csegerie/miniconda3/envs/mne_dev/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
>     r = call_item()
>   File "/storage/store/work/csegerie/miniconda3/envs/mne_dev/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
>     return self.fn(*self.args, **self.kwargs)
>   File "/storage/store/work/csegerie/miniconda3/envs/mne_dev/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
>     return self.func(*args, **kwargs)
>   File "/storage/store/work/csegerie/miniconda3/envs/mne_dev/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
>     return [func(*args, **kwargs)
>   File "/storage/store/work/csegerie/miniconda3/envs/mne_dev/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
>     return [func(*args, **kwargs)
>   File "/storage/store/work/csegerie/parietal/mne-bids-pipeline/scripts/preprocessing/02-frequency_filter.py", line 124, in run_filter
>     raw_er.save(raw_er_fname_out, overwrite=True, split_naming='bids')
>   File "<decorator-gen-187>", line 24, in save
>   File "/storage/store/work/csegerie/parietal/mne-python/mne/io/base.py", line 1449, in save
>     _write_raw(fname, self, info, picks, fmt, data_type, reset_range,
>   File "/storage/store/work/csegerie/parietal/mne-python/mne/io/base.py", line 2108, in _write_raw
>     final_fname = _write_raw_fid(
>   File "/storage/store/work/csegerie/parietal/mne-python/mne/io/base.py", line 2137, in __exit__
>     os.remove(self.fname)
> FileNotFoundError: [Errno 2] No such file or directory: '/storage/store2/data/time_in_wm_new/derivatives/mne-bids-pipeline/sub-197/meg/sub-197_task-noise_proc-filt_split-01_raw.fif'
> """

**Comment by agramfort** [comment] 2021-06-10 14:14
I've observed the same thing yesterday. No idea what's going on.

>

**Comment by hoechenberger** [comment] 2021-06-10 15:11
It **shouldn't** be named `_split-*` under normal circumstances. So it appears to me it's actually saved in the right place, but trying to read it is where we have a problem (i.e., we're generating an incorrect filename)

**Comment by hoechenberger** [comment] 2021-06-23 10:00
I will look into this.

**Comment by hoechenberger** [comment] 2021-06-23 12:30
I cannot reproduce with the time in working memory data and the `main` branch of the pipeline. The problem may just have disappeared during our massive refactorings and changes over the past few days… @crsegerie Can you try with latest `main`?

**Comment by hoechenberger** [comment] 2021-06-23 16:13
Tried again with just a single participant and cannot reproduce either. Closing for now, but feel free to re-open should you come across this issue again

**Closed** 2021-06-23 16:13 UTC
Labels: bug
